from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

from asset_studio.project.asset_database import AssetDatabase
from asset_studio.textures.procedural_texture_engine import ProceduralTextureEngine


@dataclass
class AssetStudioContext:
    workspace_root: Path
    texture_engine: ProceduralTextureEngine
    asset_db: AssetDatabase

    def write_json(self, path: Path, payload: dict) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    def write_texture(self, path: Path, image: Image.Image) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        image.save(path, format="PNG")

    def add_lang_entry(self, key: str, value: str) -> None:
        lang_path = self.workspace_root / "assets" / "lang" / "en_us.json"
        if lang_path.exists():
            payload = json.loads(lang_path.read_text(encoding="utf-8"))
        else:
            payload = {}
        payload[key] = value
        self.write_json(lang_path, payload)

    def append_to_tag(self, path: Path, value: str) -> None:
        payload = {"replace": False, "values": []}
        if path.exists():
            payload = json.loads(path.read_text(encoding="utf-8"))
            payload.setdefault("replace", False)
            payload.setdefault("values", [])
        if value not in payload["values"]:
            payload["values"].append(value)
        self.write_json(path, payload)

    def write_preview_snapshot(self, model_name: str) -> None:
        preview = self.workspace_root / "previews" / f"{model_name}.txt"
        preview.parent.mkdir(parents=True, exist_ok=True)
        preview.write_text(f"Preview snapshot placeholder for {model_name}\n", encoding="utf-8")


class WorkspaceManager:
    def __init__(self, workspace_root: Path) -> None:
        self.workspace_root = workspace_root

    def initialize_workspace(self) -> AssetStudioContext:
        for rel in [
            "assets/textures/item",
            "assets/textures/block",
            "assets/models/item",
            "assets/models/block",
            "assets/blockstates",
            "assets/lang",
            "data/recipes",
            "data/loot_tables/blocks",
            "data/tags/tools",
            "blockbench",
            "previews",
            "build",
            "exports",
        ]:
            (self.workspace_root / rel).mkdir(parents=True, exist_ok=True)

        project_file = self.workspace_root / "project.json"
        if not project_file.exists():
            project_file.write_text(
                json.dumps(
                    {
                        "name": "extremecraft-asset-project",
                        "version": 1,
                        "modid": "extremecraft",
                        "description": "Generated by EXTREMECRAFT ASSET STUDIO",
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

        return AssetStudioContext(
            workspace_root=self.workspace_root,
            texture_engine=ProceduralTextureEngine(seed=1337, resolution="32x"),
            asset_db=AssetDatabase(self.workspace_root / "asset_database.json"),
        )

    def load_context(self) -> AssetStudioContext:
        return self.initialize_workspace()

    def save_context(self, context: AssetStudioContext) -> None:
        marker = context.workspace_root / "project.json"
        if not marker.exists():
            self.initialize_workspace()
