from __future__ import annotations


def basic_advancement(title: str, item: str) -> dict:
    return {
        "display": {
            "icon": {"item": item},
            "title": title,
            "description": "Generated by Asset Studio",
            "frame": "task",
            "show_toast": True,
            "announce_to_chat": False,
            "hidden": False,
        },
        "criteria": {
            "has_item": {
                "trigger": "minecraft:inventory_changed",
                "conditions": {
                    "items": [{"items": [item]}],
                },
            }
        },
    }
