
[client]
	allowOffhandBlockBreaking = true
	blacklistedItems = ["minecraft:debug_stick"]
	enableDualWield = true
	enableXPBarOverlay = true
	#Range: 0.75 ~ 1.75
	guiScaleMultiplier = 1.0
	#Range: 0.5 ~ 2.0
	skillTreeZoom = 1.0
	showSkillNodeTooltips = true

